# Generated by Django 4.1.13 on 2024-03-17 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codingai', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
